import { Theme } from "theme.slint";

export component DesktopScreen inherits Rectangle {
    background: Theme.surface_bg;

    Text {
        width: parent.width;
        height: parent.height;
        text: "Рабочий стол";
        color: Theme.text_muted;
        font-size: Theme.font_lg;
        font-weight: 700;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}

